name: school_trip_app
description: "Daejeon Daeshin High School Math Trip App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

  cupertino_icons: ^1.0.8
  connectivity_plus: ^3.0.6
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/

    - assets/app_bar_icons/
    - assets/app_bar_icons/travel_icons/

    - assets/bottom_nav_bar_icons/

    - assets/emergency_screen_icons/
    - assets/emergency_screen_images/

    - assets/travel_background_imgaes/
    - assets/travel_background_imgaes/store_images/
    - assets/travel_detail_icons/

    - assets/travel_detail_images/odaiba_images/

    - assets/travel_detail_images/disneyland_images/
    - assets/travel_detail_images/disney_hundred_images/

    - assets/travel_detail_images/hakone_sinsa_images/
    - assets/travel_detail_images/shinjukuhotel_images/
    - assets/travel_detail_images/shabuyo_images/
    - assets/travel_detail_images/odaiba_ocean_buffet_images/

    - assets/travel_detail_images/akihabara_images/
    - assets/travel_detail_images/akihabara_images/review_images/

    - assets/travel_detail_images/asakusa_images/

    - assets/travel_detail_images/odaiba_ocean_buffet_images/

    - assets/store_map_images/

    - assets/place_screen_images/

    - assets/tool_screen_icons/

    - assets/nation_images/

    - assets/main_screen_images/

    - assets/icons/

    - assets/icons/checklist.svg

    - assets/main_screen_images/
    - assets/icons/
    - assets/icons/checklist.svg
    - assets/place_screen_images/

    - assets/trip_schdule_icons/

  fonts:
    - family: CookieRunOTF
      fonts:
        - asset: assets/fonts/CookieRun Black.ttf
          weight: 900 # Black font weight
        - asset: assets/fonts/CookieRun Bold.ttf
          weight: 700 # Bold font weight
        - asset: assets/fonts/CookieRun Regular.ttf
          weight: 400 # Regular font weight
    - family: Ownglyph okticon
      fonts:
        - asset: assets/fonts/okticon_bold.ttf
          weight: 700
        - asset: assets/fonts/okticon_light.ttf
          weight: 300
        - asset: assets/fonts/okticon_regular.ttf
          weight: 400
